[package]
name = "astro-algos"
version = "0.1.0"
authors = ["Joseph Angelo <joseph.angelo@swift-nav.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
assert_approx_eq = "1.1.0"
criterion = "0.3"

[[bench]]
name = "planet_benchmark"
harness = false

